### ISSUE TITLE
Resending invite bug

### ISSUE THREAD

**Issue by LitvinenkoVitalii** [flurium/babble#137]
При повторной отправке инвайта тому же юзеру сервер крашится из-за необработанной ошибки

**Comment by roman-koshchei** [comment]
Проблема била в том что часть хендлеров асинхронна и поетому внешний try catch не мог обрабативать ошибки из них. Я сделал 2 словаря хендлеров: один из асинхронних, другой из синхронних

**Comment by roman-koshchei** [comment]
@LitvinenkoVitalii протестируй все ли ок

**Comment by LitvinenkoVitalii** [comment]
@roman-koshchei Все норм работает
